name: Build Action

on:
  push:
  workflow_dispatch:

env:
  ARTIFACT_NAME: chuck_norris_facts-v${{ github.run_number }}.zip

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: powershell Move-Item -Path "build/windows/runner/Release"  -Destination "build/windows/runner/chuck_norris_facts"
      - uses: actions/upload-artifact@v3
        with:
         name: $ARTIFACT_NAME
         path: build/windows/runner
      - uses: actions/download-artifact@v3
        with:
          name: $ARTIFACT_NAME
      - uses: ncipollo/release-action@v1
        with:
          artifacts: $ARTIFACT_NAME
          artifactErrorsFailBuild: true
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          tag: v${{ github.run_number }}
          commit: ${{ github.ref_name }}
