name: Build Action

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
         name: chuck_norris_facts
         path: build/windows/runner/Release
      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: build/windows/runner/Release
          filename: chuck_norris_facts-v${{ github.run_number }}.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: chuck_norris_facts-v${{ github.run_number }}.zip
          artifactErrorsFailBuild: true
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          tag: v${{ github.run_number }}
          commit: ${{ github.ref_name }}
