name: Build Action

on:
  push:
  workflow_dispatch:

env:
  APP_NAME: chuck_norris_facts
  BUILD_PATH: build/windows/runner
  ARTIFACT_NAME: $APP_NAME-v${{ github.run_number }}.zip

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: powershell Move-Item -Path "$BUILD_PATH/Release"  -Destination "$BUILD_PATH/$APP_NAME"
      - uses: actions/upload-artifact@v3
        with:
         name: $ARTIFACT_NAME
         path: $BUILD_PATH
      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: $BUILD_PATH
          path: $APP_NAME
          filename: $ARTIFACT_NAME.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: $BUILD_PATH/$ARTIFACT_NAME.zip
          artifactErrorsFailBuild: true
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          tag: v${{ github.run_number }}
          commit: ${{ github.ref_name }}
